//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CurrWPFApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Materials
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Materials()
        {
            this.MaterialProducts = new HashSet<MaterialProducts>();
        }
    
        public int Id { get; set; }
        public string MaterialName { get; set; }
        public Nullable<int> MaterialTypeId { get; set; }
        public Nullable<double> PriceByOne { get; set; }
        public Nullable<double> HasQuantity { get; set; }
        public Nullable<double> MinQuantity { get; set; }
        public Nullable<double> QuantityInOne { get; set; }
        public string CheckStyle { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MaterialProducts> MaterialProducts { get; set; }
        public virtual MaterialType MaterialType { get; set; }
    }
}
